#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2026.
#  OFI transport data-integrity initiator (P1h multi-seg verification).

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

APP = ofi_integrity

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
