#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2026.
#  OFI transport contiguous and multi-segment data-integrity initiator.

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

APP = ofi_integrity

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
